name: Generate Snake Animation 🐍

on:
  schedule: # runs automatically every 24 hours
    - cron: "0 */24 * * *"
  workflow_dispatch: # allows manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Rufine777
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
